name: 자동 컨테이너 배포 및 태그 업데이트
on:
  push:
    branches:
      - main
jobs:
  build-deploy:
    name: 자동 컨테이너 배포 작업
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin
      - name: Get current time
        uses: josStorer/get-current-time@v2
        id: current-time
        with:
          format: yyyyMMDDHHmmss
          utcOffset: "+09:00"
      - name: Get deploy version
        run: echo "deployment-version=${{ steps.current-time.outputs.formattedTime }}" >> $GITHUB_ENV
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
        # 운영 환경 배포
      - name: Build and Deploy api server image (PROD) 🚀
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: wrapper
          cache-read-only: true
          arguments: |
            jib
            -DsendCredentialsOverHttp=true
            -Djib.container.jvmFlags=-Dspring.profiles.active=prod,-Dspring.cloud.config.server.git.password=${{ secrets.GIT_HUB_PERSONAL_ACCESS_TOKEN }}
            -Djib.from.auth.username=${{ secrets.HARBOR_USERNAME }}
            -Djib.from.auth.password=${{ secrets.HARBOR_PASSWORD }}
            -Djib.to.image=harbor.yellowsunn.com:80/prod/home-config-server
            -Djib.to.tags=${{ env.deployment-version }},latest
            -Djib.to.auth.username=${{ secrets.HARBOR_USERNAME }}
            -Djib.to.auth.password=${{ secrets.HARBOR_PASSWORD }}
            --stacktrace
      - name: Trigger Update Image tag (PROD)
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.GIT_HUB_PERSONAL_ACCESS_TOKEN }}
          repository: yellowsunn-home-server/kubernetes-manifest
          event-type: change-image-tag
          client-payload: |-
            {
              "requested-event-path": "${{ env.GITHUB_EVENT_PATH }}",
              "container-image": "harbor.yellowsunn.com:80/prod/home-config-server",
              "deployment-version": "${{ env.deployment-version }}",
              "overlay-path": "home-config-server/prod"
            }

      - name: Sleep for 30 seconds
        run: sleep 30s
        shell: bash

        # 개발 환경 배포
      - name: Build and Deploy api server image (DEV) 🚀
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: wrapper
          cache-read-only: true
          arguments: |
            jib
            -DsendCredentialsOverHttp=true
            -Djib.container.jvmFlags=-Dspring.profiles.active=dev,-Dspring.cloud.config.server.git.password=${{ secrets.GIT_HUB_PERSONAL_ACCESS_TOKEN }}
            -Djib.from.auth.username=${{ secrets.HARBOR_USERNAME }}
            -Djib.from.auth.password=${{ secrets.HARBOR_PASSWORD }}
            -Djib.to.image=harbor.yellowsunn.com:80/dev/home-config-server
            -Djib.to.tags=${{ env.deployment-version }},latest
            -Djib.to.auth.username=${{ secrets.HARBOR_USERNAME }}
            -Djib.to.auth.password=${{ secrets.HARBOR_PASSWORD }}
            --stacktrace
      - name: Trigger Update Image tag (DEV)
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.GIT_HUB_PERSONAL_ACCESS_TOKEN }}
          repository: yellowsunn-home-server/kubernetes-manifest
          event-type: change-image-tag
          client-payload: |-
            {
              "requested-event-path": "${{ env.GITHUB_EVENT_PATH }}",
              "container-image": "harbor.yellowsunn.com:80/dev/home-config-server",
              "deployment-version": "${{ env.deployment-version }}",
              "overlay-path": "home-config-server/dev"
            }
